#!/bin/sh
#
# Script called by kvm on tap interface deletion
#

printf -- "%s:\n" "${0}"
printf "Removing %s from bridge %s\n" "${1}" "${KVM_BRIDGE}"
ip link set "${1}" down
brctl delif "${KVM_BRIDGE}" "${1}"

