#!/bin/sh
#
# Script called by kvm on tap interface creation
#
KVM_BRIDGE_OPT=${KVM_BRIDGE_OPT:-''}
printf -- "%s:\n" "${0}"
printf "Adding %s to bridge interface %s with opt '%s'\n" \
	"${1}" "${KVM_BRIDGE}" "${KVM_BRIDGE_OPT}"
if [ -z "${KVM_BRIDGE_OPT}" ]; then
	ovs-vsctl add-port "${KVM_BRIDGE}" "${1}"
else
	ovs-vsctl add-port "${KVM_BRIDGE}" "${1}" ${KVM_BRIDGE_OPT:-''}
fi
ip link set "${1}" up

